name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: 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
          GIST_ID: https://gist.github.com/shining8543/ed6d806ef2b1e526634801580dcc3443
          TIMEZONE: Asia/Seoul
